import type { Metric, PanelEntry, Registry } from './types.ts';

// ── Artifact 1: the disclosure panel data structure ─────────────────────────
// Derived ONLY from the registry. The panel deliberately drops the internal
// `description`; the user sees the plain-language `disclosure` line plus expiry.
export function buildPanel(reg: Registry): PanelEntry[] {
  return reg.metrics.map((m) => ({
    name: m.name,
    type: m.type,
    disclosure: m.disclosure,
    expires: m.expires,
  }));
}

// ── Artifact 2: typed client instrumentation calls ──────────────────────────
// Emits a TS module: a frozen METRIC_NAMES set, a MetricName union, and one
// typed emit helper per metric. Because the app can only call generated helpers,
// an emit site for an undeclared counter is a TypeScript error — the Glean-style
// "you cannot emit what you did not declare" gate, enforced at build (typecheck),
// not by convention.
function tsIdent(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}

export function generateClientSource(reg: Registry): string {
  const names = reg.metrics.map((m) => m.name);
  const lines: string[] = [];
  lines.push('// GENERATED by measure-proof/registry — do not hand-edit.');
  lines.push('// Source of truth: registry/metrics.yaml');
  lines.push('');
  lines.push('export const METRIC_NAMES = [');
  for (const n of names) lines.push(`  ${JSON.stringify(n)},`);
  lines.push('] as const;');
  lines.push('export type MetricName = (typeof METRIC_NAMES)[number];');
  lines.push('');
  lines.push('export interface MetricMeta {');
  lines.push('  name: MetricName;');
  lines.push("  type: 'page' | 'feature' | 'timing' | 'edge';");
  lines.push('  expires: string;');
  lines.push('  from?: string;');
  lines.push('  to?: string;');
  lines.push('}');
  lines.push('');
  lines.push('export const METRIC_META: Record<MetricName, MetricMeta> = {');
  for (const m of reg.metrics) {
    const meta =
      m.type === 'edge'
        ? `{ name: ${JSON.stringify(m.name)}, type: 'edge', expires: ${JSON.stringify(m.expires)}, from: ${JSON.stringify(m.from)}, to: ${JSON.stringify(m.to)} }`
        : `{ name: ${JSON.stringify(m.name)}, type: ${JSON.stringify(m.type)}, expires: ${JSON.stringify(m.expires)} }`;
    lines.push(`  ${JSON.stringify(m.name)}: ${meta},`);
  }
  lines.push('};');
  lines.push('');
  lines.push('// One typed helper per declared metric.');
  lines.push('export interface Emitter { emit(name: MetricName): void; }');
  for (const m of reg.metrics) {
    lines.push(
      `export const ${tsIdent(m.name)} = (e: Emitter): void => e.emit(${JSON.stringify(m.name)});`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

// Structured metric metadata — the runtime companion to the emitted
// METRIC_META in generateClientSource. The generated client honors `expires`
// from this at runtime (E6).
export interface MetricMeta {
  name: string;
  type: Metric['type'];
  expires: string;
  from?: string;
  to?: string;
}

export function buildMeta(reg: Registry): Record<string, MetricMeta> {
  const out: Record<string, MetricMeta> = {};
  for (const m of reg.metrics) {
    out[m.name] = {
      name: m.name,
      type: m.type,
      expires: m.expires,
      ...(m.type === 'edge' ? { from: m.from, to: m.to } : {}),
    };
  }
  return out;
}

// ── Artifact 3: test fixtures ───────────────────────────────────────────────
export interface Fixtures {
  counterNames: string[];
  edges: { name: string; from: string; to: string }[];
  /** A zeroed counter bag with exactly the declared counters — nothing else. */
  zeroBag: Record<string, number>;
}

export function buildFixtures(reg: Registry): Fixtures {
  const zeroBag: Record<string, number> = {};
  for (const m of reg.metrics) zeroBag[m.name] = 0;
  return {
    counterNames: reg.metrics.map((m) => m.name),
    edges: reg.metrics
      .filter((m): m is Metric & { from: string; to: string } => m.type === 'edge')
      .map((m) => ({ name: m.name, from: m.from, to: m.to })),
    zeroBag,
  };
}

// ── Drift gate: emit-without-registry-entry ─────────────────────────────────
// Given the set of counter names an instrumentation source references, return an
// error for every name the registry does not declare. Empty array = clean build.
export function lintEmitSites(usedNames: string[], reg: Registry): string[] {
  const errs: string[] = [];
  for (const name of usedNames) {
    if (!reg.byName.has(name)) {
      errs.push(`emit site references undeclared counter \`${name}\` (not in registry)`);
    }
  }
  return errs;
}

// ── Build-time expiry lint (E6) ─────────────────────────────────────────────
export interface ExpiryLint {
  expired: string[];
  warnings: string[];
}

/** `today` as YYYY-MM-DD; ISO dates compare correctly as strings. */
export function lintExpired(reg: Registry, today: string): ExpiryLint {
  const expired: string[] = [];
  const warnings: string[] = [];
  for (const m of reg.metrics) {
    if (m.expires < today) {
      expired.push(m.name);
      warnings.push(`metric \`${m.name}\` expired on ${m.expires} (today ${today})`);
    }
  }
  return { expired, warnings };
}
