// User guide page (user-guide.html): a static, no-auth help page. Narrative
// entries covering the app's features, each with a TOC anchor; the visual ones
// carry real screenshots (assets/guide/, regenerated by tools/guide-shots.mjs).
// Reached from Settings → About.
import { expect, test } from '@playwright/test';

test('the guide opens with the Bluesky explainer and a working table of contents', async ({
  page,
}) => {
  await page.goto('/user-guide.html');
  await expect(page.getByTestId('user-guide-title')).toBeVisible();

  // Plain-English Bluesky tie-in leads.
  const bluesky = page.getByTestId('guide-entry-bluesky');
  await expect(bluesky).toBeVisible();
  await expect(bluesky).toContainText(/Bluesky/);

  // TOC → anchor navigation lands on the entry.
  const toc = page.getByTestId('guide-toc');
  await expect(toc).toBeVisible();
  await toc.locator('a[href="#guide-entry-meals"]').click();
  await expect(page).toHaveURL(/#guide-entry-meals/);
  await expect(page.getByTestId('guide-entry-meals')).toBeInViewport();
});

test('every screenshot in the guide actually loads from assets/guide', async ({ page }) => {
  await page.goto('/user-guide.html');
  const images = page.locator('.guide-entry img');
  const count = await images.count();
  expect(count).toBeGreaterThanOrEqual(8);
  for (let i = 0; i < count; i += 1) {
    const img = images.nth(i);
    await img.scrollIntoViewIfNeeded();
    // naturalWidth 0 = a broken src (asset missing from the build).
    await expect
      .poll(async () => img.evaluate((node) => (node as HTMLImageElement).naturalWidth))
      .toBeGreaterThan(0);
  }
});

test('the user guide keeps the share-to-import walkthrough', async ({ page }) => {
  await page.goto('/user-guide.html');
  const share = page.getByTestId('guide-entry-share');
  await share.scrollIntoViewIfNeeded();
  await expect(share).toBeVisible();
  await expect(share.locator('h3')).toContainText(/shar(e|ing)/i);
  // Honest constraints are present, not buried.
  await expect(share).toContainText(/Android/i);
  await expect(share).toContainText(/Publish/i);
});

test('Settings links to the user guide', async ({ page }) => {
  await page.goto('/settings.html');
  const link = page.getByTestId('settings-user-guide');
  await expect(link).toBeVisible();
  await expect(link).toHaveAttribute('href', './user-guide.html');
  await link.click();
  await expect(page).toHaveURL(/user-guide\.html/);
  await expect(page.getByTestId('guide-entry-share')).toBeVisible();
});
