// The guide section index (RUN-GUIDE-HELPER Layer A, D1/D2).
//
// The user guide's source is src/pages/user-guide-view.ts — a DOM builder, not
// Markdown — so the index is GENERATED by walking the RENDERED guide DOM rather
// than hand-maintained: it cannot drift from the guide because it IS the guide,
// read back. The same pure walk runs in two places: in the browser over the live
// guide (question-box wiring) and at build time over a happy-dom render (the D2
// anchor-validity gate + the shipped guide-index.json). One walk, one truth.
//
// The walk is heading-based and general (it handles nested headings and
// breadcrumb chains, exercised by fixtures) even though the real guide is a flat
// list of sibling sections — so a future nested guide indexes correctly with no
// change here.

/** One indexed guide section. The anchor is a stable id present in the rendered
 *  guide; a result links to `#{anchor}`. `phrasings` is Layer B (empty until
 *  Phase 3); everything else is derived from the section's own content. */
export interface GuideSection {
  /** Stable id, must exist in the rendered guide. */
  anchor: string;
  /** The section heading text. */
  title: string;
  /** Ancestor heading titles, outermost first (display + weak search signal). */
  breadcrumb: string[];
  /** The section's own body text — child sections excluded (no double counting). */
  text: string;
  /** Curated alternate question phrasings (Layer B); empty in Layer A. */
  phrasings: string[];
}

const HEADING = /^H([1-6])$/;

/** Collapse whitespace and trim — the guide's DOM prose has incidental newlines
 *  and indentation from the builder. */
const normalize = (s: string): string => s.replace(/\s+/g, ' ').trim();

/** The nearest ancestor-or-self element (below `root`) that carries an id — the
 *  guide wraps each entry's heading in `<section id="…">`, so a heading's own id
 *  is rare but supported. Returns null if nothing between the node and root has
 *  one. */
const idBearer = (from: Element, root: Element): Element | null => {
  let el: Element | null = from;
  while (el !== null && el !== root) {
    if (el.id !== '') return el;
    el = el.parentElement;
  }
  return null;
};

/** True when a text node sits inside a heading element — that text is the
 *  section title, not body, so it is never folded into `text`. */
const insideHeading = (text: Text): boolean =>
  text.parentElement?.closest('h1,h2,h3,h4,h5,h6') != null;

/** Read a section's curated phrasings from its `data-phrasings` JSON attribute
 *  (Layer B). Absent/malformed → none: help must never break on bad data. */
const phrasingsOf = (bearer: Element | null): string[] => {
  const raw = bearer?.getAttribute('data-phrasings');
  if (raw == null || raw === '') return [];
  try {
    const parsed: unknown = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter((x): x is string => typeof x === 'string') : [];
  } catch {
    return [];
  }
};

type Open = {
  bearer: Element | null;
  heading: HTMLElement;
  breadcrumb: string[];
  parts: string[];
};

/**
 * Walk a rendered guide root and emit one GuideSection per anchor-bearing
 * heading, in document order. A heading opens a section; every text node is
 * attributed to the MOST RECENT heading, so a parent section's `text` naturally
 * excludes its child sections' text (no double counting). Sections with no
 * resolvable anchor (e.g. the page's own `<h2>` title, which has no id) or no
 * body text are skipped — they can still contribute a breadcrumb for children.
 */
export const buildGuideIndex = (root: HTMLElement): GuideSection[] => {
  const doc = root.ownerDocument;
  const walker = doc.createTreeWalker(root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
  const stack: { level: number; title: string }[] = [];
  const sections: GuideSection[] = [];
  let current: Open | null = null;

  const close = (): void => {
    if (current === null) return;
    const anchor = current.bearer?.id ?? '';
    const text = normalize(current.parts.join(' '));
    if (anchor !== '' && text !== '') {
      sections.push({
        anchor,
        title: normalize(current.heading.textContent ?? ''),
        breadcrumb: current.breadcrumb,
        text,
        phrasings: phrasingsOf(current.bearer),
      });
    }
    current = null;
  };

  for (let node = walker.nextNode(); node !== null; node = walker.nextNode()) {
    if (node.nodeType === 1 /* element */) {
      const el = node as HTMLElement;
      const m = HEADING.exec(el.tagName);
      if (m === null) continue;
      close();
      const level = Number(m[1]);
      while (stack.length > 0 && stack[stack.length - 1]!.level >= level) stack.pop();
      const breadcrumb = stack.map((s) => s.title);
      current = { bearer: idBearer(el, root), heading: el, breadcrumb, parts: [] };
      stack.push({ level, title: normalize(el.textContent ?? '') });
    } else if (current !== null && !insideHeading(node as Text)) {
      current.parts.push((node as Text).data);
    }
  }
  close();
  return sections;
};

/** Every element id present under `root` (inclusive) — the D2 gate's truth set. */
export const collectAnchorIds = (root: HTMLElement): Set<string> => {
  const ids = new Set<string>();
  if (root.id !== '') ids.add(root.id);
  for (const el of root.querySelectorAll('[id]')) ids.add(el.id);
  return ids;
};

/** D2: fail loudly if any emitted anchor is not a real id in the rendered guide.
 *  A help system that points at a section that no longer exists is worse than
 *  none — so this is a hard gate at build time, never a warning. */
export const assertValidAnchors = (
  sections: readonly GuideSection[],
  ids: ReadonlySet<string>,
): void => {
  const missing = sections.map((s) => s.anchor).filter((a) => !ids.has(a));
  if (missing.length > 0) {
    throw new Error(
      `guide index: ${missing.length} anchor(s) absent from the rendered guide: ${missing.join(', ')}`,
    );
  }
};

/** Deterministic serialization (test 5): sections in document order, fixed key
 *  order, stable formatting — byte-identical across rebuilds from identical
 *  input, so the shipped guide-index.json never churns spuriously. */
export const serializeGuideIndex = (sections: readonly GuideSection[]): string => {
  const stable = sections.map((s) => ({
    anchor: s.anchor,
    title: s.title,
    breadcrumb: [...s.breadcrumb],
    text: s.text,
    phrasings: [...s.phrasings],
  }));
  return `${JSON.stringify(stable, null, 2)}\n`;
};
