// The catalogue's explicitly-URL'd entries (Mexican + American "Verified
// URLs from research include:" lines). Category drives recipeCuisine.
// NON-PRODUCTION ops tooling — the proving batch for the JSON-LD extractor.
export const BATCH_URLS = [
  { name: 'Guacamole', category: 'Mexican', url: 'https://www.isabeleats.com/simple-guacamole-recipe/' },
  { name: 'Pico de Gallo', category: 'Mexican', url: 'https://www.isabeleats.com/mexican-pico-de-gallo-recipe/' },
  { name: 'Chicken Tinga', category: 'Mexican', url: 'https://www.mexicoinmykitchen.com/chicken-tinga-recipe/' },
  { name: 'Carnitas', category: 'Mexican', url: 'https://www.isabeleats.com/mexican-slow-cooker-pork-carnitas-tacos/' },
  { name: 'Beef Barbacoa', category: 'Mexican', url: 'https://www.isabeleats.com/pressure-cooker-barbacoa-beef/' },
  { name: 'Cheese Enchiladas', category: 'Mexican', url: 'https://www.isabeleats.com/cheese-enchiladas/' },
  { name: 'Chicken Enchiladas', category: 'Mexican', url: 'https://www.isabeleats.com/red-chicken-enchiladas/' },
  { name: 'Chiles Rellenos', category: 'Mexican', url: 'https://www.mexicoinmykitchen.com/chile-relleno-recipe/' },
  { name: 'Pozole Rojo', category: 'Mexican', url: 'https://www.isabeleats.com/red-posole-recipe/' },
  { name: 'Pork Tamales', category: 'Mexican', url: 'https://tastesbetterfromscratch.com/mexican-tamales/' },
  { name: 'Elote', category: 'Mexican', url: 'https://www.isabeleats.com/authentic-mexican-street-corn/' },
  { name: 'Refried Beans', category: 'Mexican', url: 'https://www.isabeleats.com/authentic-mexican-refried-beans/' },
  { name: 'Mexican Rice', category: 'Mexican', url: 'https://www.isabeleats.com/moms-authentic-mexican-rice/' },
  { name: 'Chicken Fajitas', category: 'Mexican', url: 'https://www.isabeleats.com/30-minute-mexican-lime-chicken-fajitas-easy-guacamole/' },
  { name: 'Ground Beef Tacos', category: 'Mexican', url: 'https://www.isabeleats.com/easy-ground-beef-tacos/' },
  { name: 'Birria Tacos', category: 'Mexican', url: 'https://www.isabeleats.com/birria-tacos/' },
  { name: 'Salsa Verde', category: 'Mexican', url: 'https://www.isabeleats.com/homemade-tomatillo-salsa-verde/' },
  { name: 'Ceviche', category: 'Mexican', url: 'https://www.mexicoinmykitchen.com/mexican-ceviche-recipe/' },
  { name: 'Huevos Rancheros', category: 'Mexican', url: 'https://www.isabeleats.com/easy-huevos-rancheros-recipe/' },
  { name: 'Chilaquiles Rojos', category: 'Mexican', url: 'https://www.isabeleats.com/easy-red-chilaquiles-recipe/' },
  { name: 'Classic Cheeseburger', category: 'American', url: 'https://www.seriouseats.com/ultra-smashed-cheeseburger-recipe-food-lab' },
  { name: 'Mac and Cheese', category: 'American', url: 'https://www.seriouseats.com/ingredient-stovetop-mac-and-cheese-recipe' },
  { name: 'BBQ Pulled Pork', category: 'American', url: 'https://www.recipetineats.com/pulled-pork-with-bbq-sauce/' },
  { name: 'Southern Fried Chicken', category: 'American', url: 'https://www.recipetineats.com/fried-chicken/' },
  { name: 'Cobb Salad', category: 'American', url: 'https://www.recipetineats.com/cobb-salad/' },
  { name: 'Caesar Salad', category: 'American', url: 'https://www.recipetineats.com/chicken-caesar-salad/' },
  { name: 'Chili con Carne', category: 'American', url: 'https://www.recipetineats.com/chilli-con-carne/' },
  { name: 'Coleslaw', category: 'American', url: 'https://www.recipetineats.com/coleslaw/' },
  { name: 'Classic Potato Salad', category: 'American', url: 'https://www.simplyrecipes.com/recipes/classic_potato_salad/' },
  { name: 'Sloppy Joes', category: 'American', url: 'https://www.recipetineats.com/sloppy-joes/' },
  { name: 'Banana Bread', category: 'American', url: 'https://www.simplyrecipes.com/recipes/banana_bread/' },
];
